#ifndef CNN_ACCEL_ABI_H
#define CNN_ACCEL_ABI_H

#include <stdint.h>
#include "cnn_accel_abi_constants.h"

/* Frozen V1 model-package ABI. Records are serialized explicitly; do not cast
 * untrusted package memory to native C structs. */
#define CNN_CONTROL_START                   (1u << 0)
#define CNN_CONTROL_CLEAR                   (1u << 1)
#define CNN_STATUS_BUSY                     (1u << 0)
#define CNN_STATUS_DONE                     (1u << 1)
#define CNN_STATUS_ERROR                    (1u << 2)
#define CNN_STATUS_LAYER_DONE               (1u << 3)
#define CNN_STATUS_MODEL_ACTIVE             (1u << 4)
#define CNN_STATUS_ACTIVE_LAYER_SHIFT       5u
#define CNN_STATUS_ACTIVE_LAYER_MASK        (7u << CNN_STATUS_ACTIVE_LAYER_SHIFT)
#define CNN_STATUS_PARAMETER_BANK_SHIFT     12u
#define CNN_STATUS_PARAMETER_BANK_MASK      (3u << CNN_STATUS_PARAMETER_BANK_SHIFT)
#define CNN_IRQ_DONE                        (1u << 0)
#define CNN_IRQ_ERROR                       (1u << 1)

#define CNN_MODEL_COMMAND_BEGIN_LOAD   (1u << 0)
#define CNN_MODEL_COMMAND_FINISH_LOAD  (1u << 1)
#define CNN_MODEL_COMMAND_VALIDATE     (1u << 2)
#define CNN_MODEL_COMMAND_ACTIVATE     (1u << 3)
#define CNN_MODEL_COMMAND_RETIRE       (1u << 4)
#define CNN_MODEL_COMMAND_CLEAR_ERROR  (1u << 5)

#define CNN_DMA_PACKET_MAGIC           0x31504E43u
#define CNN_DMA_PACKET_VERSION                  1u
#define CNN_DMA_PACKET_HEADER_WORDS             8u
#define CNN_DMA_PACKET_HEADER_BYTES             32u
#define CNN_DMA_PACKET_INPUT_TILE                 1u
#define CNN_DMA_PACKET_LAYER_WEIGHTS              2u
#define CNN_DMA_PACKET_LAYER_BIASES               3u
#define CNN_DMA_PACKET_OUTPUT_TILE                4u

enum cnn_model_staging_state {
    CNN_MODEL_STAGING_UNLOADED = 0,
    CNN_MODEL_STAGING_LOADING = 1,
    CNN_MODEL_STAGING_LOADED_UNVALIDATED = 2,
    CNN_MODEL_STAGING_VALIDATED = 3
};

enum cnn_model_lifecycle_error {
    CNN_MODEL_LIFECYCLE_OK = 0,
    CNN_MODEL_LIFECYCLE_BAD_STATE = 1,
    CNN_MODEL_LIFECYCLE_BUSY = 2,
    CNN_MODEL_LIFECYCLE_BAD_ADDRESS = 3,
    CNN_MODEL_LIFECYCLE_INCOMPLETE = 4,
    CNN_MODEL_LIFECYCLE_BAD_HEADER = 5,
    CNN_MODEL_LIFECYCLE_LIMIT = 6,
    CNN_MODEL_LIFECYCLE_BAD_DESCRIPTOR = 7
};

#define CNN_METADATA_KIND_HEADER        0u
#define CNN_METADATA_KIND_LAYER         1u
#define CNN_METADATA_KIND_TENSOR        2u
#define CNN_METADATA_KIND_QUANTIZATION  3u
#define CNN_METADATA_ADDRESS(kind, record, word) \
    ((((uint32_t)(word) & 0x3Fu) << 8) | \
     (((uint32_t)(record) & 0x3Fu) << 2) | ((uint32_t)(kind) & 0x3u))

enum cnn_error_code {
    CNN_ERROR_NONE = 0x0000,
    CNN_ERROR_PACKAGE_VALIDATION_FAILED = 0x0101,
    CNN_ERROR_MODEL_ABI_UNSUPPORTED = 0x0102,
    CNN_ERROR_CAPABILITY_FEATURE_MISSING = 0x0201,
    CNN_ERROR_CAPABILITY_LIMIT_EXCEEDED = 0x0202,
    CNN_ERROR_UNSUPPORTED_OPERATION = 0x0203,
    CNN_ERROR_MODEL_LIFECYCLE_FAILED = 0x0300,
    CNN_ERROR_EXECUTION_FAILED = 0x0301,
    CNN_ERROR_PARAMETER_VALIDATION_FAILED = 0x0302,
    CNN_ERROR_DATA_PLANE_PROTOCOL = 0x0400
};

enum cnn_error_stage {
    CNN_ERROR_STAGE_NONE = 0,
    CNN_ERROR_STAGE_PACKAGE_LOAD = 1,
    CNN_ERROR_STAGE_PACKAGE_VALIDATE = 2,
    CNN_ERROR_STAGE_MODEL_ACTIVATE = 3,
    CNN_ERROR_STAGE_EXECUTE = 4,
    CNN_ERROR_STAGE_DATA_PLANE = 5
};

enum cnn_error_record_kind {
    CNN_ERROR_RECORD_NONE = 0,
    CNN_ERROR_RECORD_MODEL = 1,
    CNN_ERROR_RECORD_LAYER = 2,
    CNN_ERROR_RECORD_TENSOR = 3,
    CNN_ERROR_RECORD_QUANTIZATION = 4,
    CNN_ERROR_RECORD_PACKET = 5
};

enum cnn_error_field {
    CNN_ERROR_FIELD_NONE = 0,
    CNN_ERROR_FIELD_ABI_VERSION = 1,
    CNN_ERROR_FIELD_FEATURE_FLAGS = 2,
    CNN_ERROR_FIELD_LAYER_COUNT = 3,
    CNN_ERROR_FIELD_TENSOR_COUNT = 4,
    CNN_ERROR_FIELD_QUANTIZATION_COUNT = 5,
    CNN_ERROR_FIELD_WIDTH = 6,
    CNN_ERROR_FIELD_HEIGHT = 7,
    CNN_ERROR_FIELD_INPUT_CHANNELS = 8,
    CNN_ERROR_FIELD_OUTPUT_CHANNELS = 9,
    CNN_ERROR_FIELD_OPCODE = 10,
    CNN_ERROR_FIELD_KERNEL_SIZE = 11,
    CNN_ERROR_FIELD_STRIDE = 12,
    CNN_ERROR_FIELD_PADDING = 13,
    CNN_ERROR_FIELD_WEIGHT_BYTES = 14,
    CNN_ERROR_FIELD_BIAS_BYTES = 15,
    CNN_ERROR_FIELD_ELEMENT_TYPE = 16,
    CNN_ERROR_FIELD_ACTIVATION = 17,
    CNN_ERROR_FIELD_ROUNDING_MODE = 18,
    CNN_ERROR_FIELD_RESIDUAL_MODE = 19,
    CNN_ERROR_FIELD_PACKET_TYPE = 20,
    CNN_ERROR_FIELD_PAYLOAD_LENGTH = 21,
    CNN_ERROR_FIELD_TENSOR_ELEMENTS = 22,
    CNN_ERROR_FIELD_QUANT_MULTIPLIER = 23,
    CNN_ERROR_FIELD_QUANT_SHIFT = 24,
    CNN_ERROR_FIELD_OUTPUT_ZERO_POINT = 25
};

enum cnn_opcode {
    CNN_OPCODE_CONV2D = 1
};

enum cnn_activation {
    CNN_ACTIVATION_NONE = 0,
    CNN_ACTIVATION_RELU = 1
};

enum cnn_residual_mode {
    CNN_RESIDUAL_NONE = 0,
    CNN_RESIDUAL_POST_QUANT_ADD = 1,
    CNN_RESIDUAL_POST_QUANT_SUBTRACT = 2
};

enum cnn_rounding_mode {
    CNN_ROUND_ARITHMETIC_SHIFT = 0,
    CNN_ROUND_HALF_TO_EVEN = 1
};

enum cnn_element_type {
    CNN_ELEMENT_INT8 = 1
};

enum cnn_tensor_layout {
    CNN_LAYOUT_NHWC = 1
};

#define CNN_LAYER_FLAG_BIAS_ENABLE  (1u << 0)
#define CNN_LAYER_FLAG_LAST_LAYER   (1u << 1)
#define CNN_TENSOR_FLAG_MODEL_INPUT (1u << 0)
#define CNN_TENSOR_FLAG_MODEL_OUTPUT (1u << 1)
#define CNN_TENSOR_FLAG_CONSTANT    (1u << 2)

#endif
