/* Generated by scripts/generate_abi_constants.py. Do not edit. */
#ifndef CNN_ACCEL_ABI_CONSTANTS_H
#define CNN_ACCEL_ABI_CONSTANTS_H

#define CNN_ABI_VERSION                             0x00000001u
#define CNN_REGISTER_MAP_VERSION                    0x00050001u
#define CNN_MODEL_MAGIC                             0x314E4E43u
#define CNN_MODEL_HEADER_SIZE                       0x00000080u
#define CNN_LAYER_DESCRIPTOR_SIZE                   0x00000080u
#define CNN_TENSOR_DESCRIPTOR_SIZE                  0x00000040u
#define CNN_QUANT_DESCRIPTOR_SIZE                   0x000000C0u
#define CNN_CAPABILITY_RECORD_SIZE                  0x00000080u
#define CNN_ERROR_RECORD_SIZE                       0x00000040u
#define CNN_ABI_RECORD_ALIGNMENT                    0x00000040u
#define CNN_POSTPROCESS_ENTRY_SIZE                  0x00000010u
#define CNN_NO_TENSOR_ID                            0x0000FFFFu
#define CNN_MAX_LAYERS                              0x00000008u
#define CNN_MAX_TENSORS                             0x00000020u
#define CNN_MAX_QUANTIZATIONS                       0x00000020u
#define CNN_MAX_CHANNELS                            0x00000010u
#define CNN_MAX_TENSOR_WIDTH                        0x00000400u
#define CNN_MAX_TENSOR_HEIGHT                       0x00000400u
#define CNN_MAX_LAYER_WEIGHT_BYTES                  0x00000900u
#define CNN_MAX_LAYER_BIAS_BYTES                    0x00000040u
#define CNN_WEIGHT_BANK_CAPACITY_BYTES              0x00001000u
#define CNN_POSTPROCESS_BANK_CAPACITY_BYTES         0x00000100u
#define CNN_BIAS_BANK_CAPACITY_BYTES CNN_POSTPROCESS_BANK_CAPACITY_BYTES

#define CNN_REG_CONTROL                             0x000u
#define CNN_REG_STATUS                              0x004u
#define CNN_REG_IRQ_STATUS                          0x008u
#define CNN_REG_IRQ_ENABLE                          0x00Cu
#define CNN_REG_JOB_ID                              0x010u
#define CNN_REG_PARAMETER_LAYER                     0x014u
#define CNN_REG_MODEL_COMMAND                       0x018u
#define CNN_REG_MODEL_STATUS                        0x01Cu
#define CNN_REG_ACTIVE_MODEL_ID                     0x020u
#define CNN_REG_ACTIVE_GENERATION                   0x024u
#define CNN_REG_ACTIVE_LAYER_COUNT                  0x028u
#define CNN_REG_METADATA_ADDRESS                    0x02Cu
#define CNN_REG_METADATA_DATA                       0x030u
#define CNN_REG_METADATA_COMMIT                     0x034u
#define CNN_REG_MODEL_ERROR                         0x038u
#define CNN_REG_RUNTIME_ERROR                       0x03Cu
#define CNN_REG_ACTIVE_TENSORS                      0x040u
#define CNN_REG_CURRENT_TILE                        0x044u
#define CNN_REG_COMPLETED_LAYERS                    0x048u
#define CNN_REG_COMPLETED_TILES                     0x04Cu
#define CNN_REG_PACKET_ERRORS                       0x050u
#define CNN_REG_PARAMETER_BANKS                     0x054u
#define CNN_REG_INPUT_DDR_LO                        0x058u
#define CNN_REG_INPUT_DDR_HI                        0x05Cu
#define CNN_REG_OUTPUT_DDR_LO                       0x060u
#define CNN_REG_OUTPUT_DDR_HI                       0x064u
#define CNN_REG_SATURATION_EVENTS                   0x068u
#define CNN_REG_VERSION                             0x0FCu

#define CNN_FEATURE_CAPABILITY_QUERY                0x00000001u
#define CNN_FEATURE_STRUCTURED_ERRORS               0x00000002u
#define CNN_FEATURE_MODEL_PACKAGES                  0x00000004u
#define CNN_FEATURE_RUNTIME_METADATA                0x00000008u
#define CNN_FEATURE_PACKED_DMA                      0x00000010u
#define CNN_FEATURE_DDR_TILING                      0x00000020u
#define CNN_FEATURE_AUTONOMOUS_FETCH                0x00000040u
#define CNN_FEATURE_INTERRUPTS                      0x00000080u
#define CNN_FEATURE_FIXED_NETWORK                   0x80000000u

#endif
