#!/usr/bin/env python3
"""Generate language bindings for the stable accelerator ABI constants."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "abi/cnn_accel_v1.json"
OUTPUTS = {
    "python": ROOT / "models/cnn_abi_constants.py",
    "c": ROOT / "software/zynq_baremetal/cnn_accel_abi_constants.h",
    "sv": ROOT / "rtl/include/cnn_accel_abi_constants.svh",
}


def validate(schema: dict) -> None:
    if schema["schema_version"] != 1 or schema["abi_version"] != 1:
        raise ValueError("generator supports only schema version 1 and ABI version 1")
    registers = list(schema["registers"].values())
    if len(registers) != len(set(registers)):
        raise ValueError("register addresses must be unique")
    if any(address < 0 or address > 0xFFF or address % 4 for address in registers):
        raise ValueError("register addresses must be aligned 12-bit byte offsets")
    alignment = schema["record_sizes"]["record_alignment"]
    for name, size in schema["record_sizes"].items():
        if size <= 0:
            raise ValueError(f"record size {name} must be positive")
        if name != "postprocess_entry" and size % alignment:
            raise ValueError(f"record size {name} must be {alignment}-byte aligned")


def values(schema: dict) -> dict[str, int]:
    sizes = schema["record_sizes"]
    limits = schema["limits"]
    return {
        "ABI_VERSION": schema["abi_version"],
        "REGISTER_MAP_VERSION": schema["register_map_version"],
        "MODEL_MAGIC": schema["model_magic"],
        "MODEL_HEADER_SIZE": sizes["model_header"],
        "LAYER_DESCRIPTOR_SIZE": sizes["layer_descriptor"],
        "TENSOR_DESCRIPTOR_SIZE": sizes["tensor_descriptor"],
        "QUANT_DESCRIPTOR_SIZE": sizes["quant_descriptor"],
        "CAPABILITY_RECORD_SIZE": sizes["capability_record"],
        "ERROR_RECORD_SIZE": sizes["error_record"],
        "RECORD_ALIGNMENT": sizes["record_alignment"],
        "POSTPROCESS_ENTRY_SIZE": sizes["postprocess_entry"],
        "NO_TENSOR_ID": 0xFFFF,
        "MAX_LAYERS": limits["layers"],
        "MAX_TENSORS": limits["tensors"],
        "MAX_QUANTIZATIONS": limits["quantizations"],
        "MAX_CHANNELS": limits["channels"],
        "MAX_TENSOR_WIDTH": limits["tensor_width"],
        "MAX_TENSOR_HEIGHT": limits["tensor_height"],
        "MAX_LAYER_WEIGHT_BYTES": limits["layer_weight_bytes"],
        "MAX_LAYER_BIAS_BYTES": limits["layer_bias_bytes"],
        "WEIGHT_BANK_CAPACITY_BYTES": limits["weight_bank_capacity_bytes"],
        "POSTPROCESS_BANK_CAPACITY_BYTES": limits["postprocess_bank_capacity_bytes"],
    }


def py_text(schema: dict) -> str:
    lines = ["# Generated by scripts/generate_abi_constants.py. Do not edit.", ""]
    for name, value in values(schema).items():
        lines.append(f"{name} = {value:#x}" if value >= 65536 else f"{name} = {value}")
    lines += ["BIAS_BANK_CAPACITY_BYTES = POSTPROCESS_BANK_CAPACITY_BYTES", ""]
    for name, value in schema["registers"].items():
        lines.append(f"REG_{name} = 0x{value:03X}")
    lines.append("")
    for name, value in schema["features"].items():
        lines.append(f"FEATURE_{name} = 0x{value:08X}")
    return "\n".join(lines) + "\n"


def c_text(schema: dict) -> str:
    lines = [
        "/* Generated by scripts/generate_abi_constants.py. Do not edit. */",
        "#ifndef CNN_ACCEL_ABI_CONSTANTS_H",
        "#define CNN_ACCEL_ABI_CONSTANTS_H",
        "",
    ]
    aliases = {
        "RECORD_ALIGNMENT": "ABI_RECORD_ALIGNMENT",
        "POSTPROCESS_ENTRY_SIZE": "POSTPROCESS_ENTRY_SIZE",
    }
    for name, value in values(schema).items():
        c_name = aliases.get(name, name)
        lines.append(f"#define CNN_{c_name:<39} 0x{value:08X}u")
    lines += [
        "#define CNN_BIAS_BANK_CAPACITY_BYTES CNN_POSTPROCESS_BANK_CAPACITY_BYTES",
        "",
    ]
    for name, value in schema["registers"].items():
        lines.append(f"#define CNN_REG_{name:<35} 0x{value:03X}u")
    lines.append("")
    for name, value in schema["features"].items():
        lines.append(f"#define CNN_FEATURE_{name:<31} 0x{value:08X}u")
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def sv_text(schema: dict) -> str:
    sv_names = {
        "MODEL_HEADER_SIZE": "MODEL_HEADER_BYTES",
        "LAYER_DESCRIPTOR_SIZE": "LAYER_DESCRIPTOR_BYTES",
        "TENSOR_DESCRIPTOR_SIZE": "TENSOR_DESCRIPTOR_BYTES",
        "QUANT_DESCRIPTOR_SIZE": "QUANT_DESCRIPTOR_BYTES",
        "CAPABILITY_RECORD_SIZE": "CAPABILITY_RECORD_BYTES",
        "ERROR_RECORD_SIZE": "ERROR_RECORD_BYTES",
        "RECORD_ALIGNMENT": "RECORD_ALIGNMENT_BYTES",
        "POSTPROCESS_ENTRY_SIZE": "POSTPROCESS_ENTRY_BYTES",
    }
    lines = ["// Generated by scripts/generate_abi_constants.py. Do not edit."]
    for name, value in values(schema).items():
        target = sv_names.get(name, name)
        if name in {"MODEL_MAGIC", "REGISTER_MAP_VERSION"}:
            lines.append(f"localparam logic [31:0] {target} = 32'h{value:08X};")
        elif name == "NO_TENSOR_ID":
            lines.append(f"localparam logic [15:0] {target} = 16'h{value:04X};")
        else:
            lines.append(f"localparam int unsigned {target} = {value};")
    lines.append("localparam int unsigned BIAS_BANK_CAPACITY_BYTES = POSTPROCESS_BANK_CAPACITY_BYTES;")
    lines.append("")
    for name, value in schema["registers"].items():
        lines.append(f"localparam logic [11:0] REG_{name} = 12'h{value:03X};")
    lines.append("")
    for name, value in schema["features"].items():
        lines.append(f"localparam logic [31:0] FEATURE_{name} = 32'h{value:08X};")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    validate(schema)
    rendered = {"python": py_text(schema), "c": c_text(schema), "sv": sv_text(schema)}
    stale = []
    for language, output in OUTPUTS.items():
        content = rendered[language]
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != content:
                stale.append(str(output.relative_to(ROOT)))
        else:
            output.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated ABI files: " + ", ".join(stale))
        return 1
    if args.check:
        print("PASS: generated ABI bindings are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
